services:
  - type: web
    name: kaajkaam-api
    runtime: node
    repo: https://github.com/rifff-fin/KAAJ_KAAM-A-Remote-job-portal-for-Bangladesh
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /

